---
version: 1

kind: experiment

build:
  dockerfile: Dockerfile


declarations:
  dataset: onera_w_mask.tar.gz
  log_dir: ./log/
  data_dir: ./onera/
  weight_dir: /outputs/
  batch_size: 512
  loss: tversky
  validation_city: cupertino
  stride: 10
  patch_size: 32
  epochs: 20
  lr: 0.001
  alpha: 0.1
  beta: 0.9
  val_cities: 12\,13\,0\,1




run:
  cmd: python train.py --dataset={{ dataset }} \
                       --log_dir={{ log_dir }} \
                       --data_dir={{ data_dir }} \
                       --weight_dir={{ weight_dir }} \
                       --batch_size={{ batch_size }} \
                       --epochs={{ epochs }} \
                       --patch_size={{ patch_size }} \
                       --stride={{ stride }} \
                       --loss={{ loss }} \
                       --alpha={{ alpha }} \
                       --beta={{ beta }} \
                       --lr={{ lr }} \
                       --val_cities={{ val_cities }}
                       --validation_city={{ validation_city }}

framework: pytorch
environment:
  resources:
    gpu:
      requests: 4
      limits: 4
  node_selector:
    polyaxon: v100-deathstar

  persistence:
    data: ['data']
    outputs: 'outputs'

logging:
  level: INFO
