---
version: 1

kind: group

build:
  dockerfile: Dockerfile

#
# hptuning:
#   random_search:
#     n_experiments: 1
#   concurrency: 3
#   seed: 3234
#   matrix:
#     lr:
#       uniform: 0.002
#     alpha:
#       uniform: 0.3
#     beta:
#       uniform: 0.7

hptuning:
  concurrency: 4
  seed: 3234
  bo:
    n_iterations: 16
    n_initial_trials: 8
    metric:
      name: validate_cd_f1scores
      optimization: maximize
    utility_function:
      acquisition_function: ucb
      kappa: 1.2
      gaussian_process:
        kernel: matern
        length_scale: 1.0
        nu: 1.9
        n_restarts_optimizer: 0

  matrix:
    lr:
      uniform: [0.001, 0.01]
    alpha:
      uniform: [0, 0.3]
    beta:
      uniform: [0.7, 1]



declarations:
  dataset: onera_w_mask.tar.gz
  log_dir: ./log/
  data_dir: ./onera/
  weight_dir: /outputs/
  batch_size: 128
  loss: tversky
  stride: 50
  patch_size: 90
  epochs: 50
  # lr: 0.01
  # alpha: 0.1
  # beta: 0.9




run:
  cmd: python train.py --dataset={{ dataset }} \
                       --log_dir={{ log_dir }} \
                       --data_dir={{ data_dir }} \
                       --weight_dir={{ weight_dir }} \
                       --batch_size={{ batch_size }} \
                       --epochs={{ epochs }} \
                       --patch_size={{ patch_size }} \
                       --stride={{ stride }} \
                       --loss={{ loss }} \
                       --alpha={{ alpha }} \
                       --beta={{ beta }} \
                       --lr={{ lr }}

framework: pytorch
environment:
  resources:
    gpu:
      requests: 4
      limits: 4
  node_selector:
    polyaxon: p4-medium

  persistence:
    data: ['data']
    outputs: 'outputs'

logging:
  level: INFO
